combine_control_expr = false
enum_discrim_align_threshold = 30
error_on_line_overflow = true
error_on_unformatted = true
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
inline_attribute_width = 100
match_arm_blocks = false
match_block_trailing_comma = true
merge_imports = true
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 30
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
version = "Two"
unstable_features = true